name: Pulumi Deploy
run-name: ${{ github.actor }} triggered Pulumi deployment 🚀
on:
  push:
    branches:
      - main

jobs:
  pulumi-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pulumi

      - name: Configure Pulumi
        run: |
          pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Deploy to Beta
        if: github.ref == 'refs/heads/beta'
        run: |
          pulumi stack select beta
          pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          pulumi stack select prod
          pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
